In [3]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.random.random(5)

array([0.68357123, 0.89704344, 0.66445256, 0.17066955, 0.46208007])

# numpy level2

In [7]:
new_math = np.array([1,2,3])

In [8]:
new_math

array([1, 2, 3])

In [10]:
type(new_math)

numpy.ndarray

In [11]:
new_ones = np.ones(3)

In [12]:
new_ones

array([1., 1., 1.])

In [13]:
new_math + new_ones

array([2., 3., 4.])

In [14]:
new_math *2

array([2, 4, 6])

In [15]:
new_ones *3

array([3., 3., 3.])

# numpy level3

In [16]:
new_math[0]

1

In [17]:
new_math[1]

2

In [19]:
new_math[-1]

3

# numpy level4

In [20]:
new_math.max()

3

In [21]:
new_math.min()

1

In [22]:
new_math.sum()

6

# numpy level5

In [3]:
x = np.array([[10,20],[30,40]])

In [4]:
x

array([[10, 20],
       [30, 40]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4)) # three rows and four columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.random.random((3,4))

array([[2.39307657e-01, 6.00163090e-04, 9.59220254e-03, 1.78060292e-01],
       [1.49845513e-01, 3.55996413e-01, 2.99856550e-01, 9.11638711e-02],
       [6.03992842e-01, 1.76388166e-01, 5.17105301e-01, 5.87882057e-01]])

# numpy level 6

In [10]:
y = np.array([[2,4],[5,6]])

In [11]:
y

array([[2, 4],
       [5, 6]])

In [12]:
x + y

array([[12, 24],
       [35, 46]])

In [14]:
x.dot(y)

array([[120, 160],
       [260, 360]])

In [15]:
y.max()

6

In [16]:
y.min()

2

# numpy level 7

indexing for matrix:
accessing value : arrayName[row,column]

In [20]:
y[0,1]

4

In [21]:
y[1, 0]

5

In [22]:
y[0:2, 1]

array([4, 6])

# numpy level 8

reshaping arrays

In [2]:
new_data = np.array([1,2,3,4,5,6])

In [3]:
new_data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# numpy level 9

In [4]:
x = np.array([[10,20],[3,40],[50,60],[70,80]])

In [5]:
x

array([[10, 20],
       [ 3, 40],
       [50, 60],
       [70, 80]])

In [7]:
np.ones((5,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])